services:
  django:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/django_videos
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ASSETS_URL=http://host.docker.internal:9000/media/uploads
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    command: >
      bash -c "
        cd /home/my-user/app &&
        pipenv install &&
        pipenv run python manage.py migrate &&
        pipenv run python manage.py createsuperuser --noinput --username admin1 --email admin@user.com || true &&
        pipenv run python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - postgres
      - rabbitmq

  django_consumer_upload_chunks:
    build: .
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    depends_on:
      - django
    command: >
      bash -c "
        echo '⏳ Aguardando RabbitMQ na porta 5672...';
        while ! nc -z rabbitmq 5672; do sleep 2; done;
        echo '✅ RabbitMQ disponível, iniciando consumidor upload chunks...';
        cd /home/my-user/app && pipenv install && pipenv run python manage.py consumer_upload_chunks_to_external_storage
      "

  django_consumer_register_processed:
    build: .
    volumes:
      - .:/home/my-user/app
      - external-storage:/media/uploads
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    depends_on:
      - django
    command: >
      bash -c "
        echo '⏳ Aguardando RabbitMQ na porta 5672...';
        while ! nc -z rabbitmq 5672; do sleep 2; done;
        echo '✅ RabbitMQ disponível, iniciando consumidor registro processamento...';
        cd /home/my-user/app && pipenv install && pipenv run python manage.py consumer_register_processed_video_path
      "

  change_media_permission:
    build: .
    user: root
    command: chown -R 1000:1000 /media/uploads
    volumes:
      - external-storage:/media/uploads
    depends_on:
      - django

volumes:
  external-storage:
    external: true
